export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SET_LOADING = 'SET_LOADING';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const START_ONGOING_ATTENDANCE = 'START_ONGOING_ATTENDANCE';
export const START_ONGOING_ATTENDANCE_FAILURE =
  'START_ONGOING_ATTENDANCE_FAILURE';

export const GET_QRCODE_DETAILS = 'GET_QRCODE_DETAILS';
export const GET_QRCODE_DETAILS_FAILURE = 'GET_QRCODE_DETAILS_FAILURE';

export const SET_RANDOM_SECURITY_QUESTION = 'SET_RANDOM_SECURITY_QUESTION';
export const CLEAR_RANDOM_SECURITY_QUESTION = 'CLEAR_RANDOM_SECURITY_QUESTION';
export const SET_RANDOM_SECURITY_QUESTION_FAILURE =
  'SET_RANDOM_SECURITY_QUESTION_FAILURE';

export const SECURITY_ANSWER_CORRECT = 'SECURITY_ANSWER_CORRECT';
export const SECURITY_ANSWER_CORRECT_INCORRECT =
  'SECURITY_ANSWER_CORRECT_INCORRECT';

export const LOAD_SECURITY_QUESTIONS = 'LOAD_SECURITY_QUESTIONS';
export const LOAD_SECURITY_QUESTIONS_ERROR = 'LOAD_SECURITY_QUESTIONS_ERROR';

export const SET_USER_SECURITY_ANSWERS = 'SET_USER_SECURITY_ANSWERS';
export const SET_USER_SECURITY_ANSWERS_ERROR =
  'SET_USER_SECURITY_ANSWERS_ERROR';

export const GET_ONGOING_ATTENDANCES = 'GET_ONGOING_ATTENDANCES';
export const GET_ONGOING_ATTENDANCES_ERROR = 'GET_ONGOING_ATTENDANCES_ERROR';

export const GET_SIGNED_ATTENDANCES = 'GET_SIGNED_ATTENDANCES';
export const GET_SIGNED_ATTENDANCES_ERROR = 'GET_SIGNED_ATTENDANCES_ERROR';

export const SET_STUDENT = 'SET_STUDENT';
export const SET_STUDENT_ERROR = 'SET_STUDENT_ERROR';

export const ADD_STUDENT = 'ADD_STUDENT';
export const ADD_STUDENT_ERROR = 'ADD_STUDENT_ERROR';
export const CLEAR_STUDENT = 'CLEAR_STUDENT';

export const ERASED_ONGOING_ATTENDANCE = 'ERASED_ONGOING_ATTENDANCE';
export const ERASED_ONGOING_ATTENDANCE_ERROR =
  'ERASED_ONGOING_ATTENDANCE_ERROR';

export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_SUCCESS_ERROR';

export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_ERROR = 'UPDATE_ACCOUNT_ERROR';

export const ADD_PROFESSOR_SUCCESS = 'ADD_PROFESSOR_SUCCESS';
export const ADD_PROFESSOR_ERROR = 'ADD_PROFESSOR_ERROR';

export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_ERROR = 'ADD_COURSE_ERROR';

export const ADD_LECTURE_ROOM_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_LECTURE_ROOM_ERROR = 'ADD_COURSE_ERROR';

export const ADD_FACULTY_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_FACULTY_ERROR = 'ADD_COURSE_ERROR';

export const LOAD_FACULTIES_SUCCESS = 'LOAD_FACULTIES_SUCCESS';
export const LOAD_FACULTIES_ERROR = 'LOAD_FACULTIES_ERROR';

export const LOAD_ATTENDANCE_SCORES_SUCCESS = 'LOAD_ATTENDANCE_SCORES_SUCCESS';
export const LOAD_ATTENDANCE_SCORES_ERROR = 'LOAD_ATTENDANCE_SCORES_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_COURSES_ERROR = 'LOAD_COURSES_ERROR';

export const CLEAR_ATTENDANCE_ALERT = 'CLEAR_ATTENDANCE_ALERT';
export const QRCODE_LOCKED = 'QRCODE_LOCKED';

export const SET_ALERT = 'SET_ALERT';
